# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

# gem "jekyll", "~> 4.2"
gem "github-pages", "~> 225", group: :jekyll_plugins

# gem "minima"
gem "minimal-mistakes-jekyll"

group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
  end